# Generated by Django 3.1.1 on 2020-09-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200911_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
